site_name: Ética y Deontología en Enfermería
site_url: https://262etica.github.io/262etica/
docs_dir: docs

nav:
  - Inicio: index.md
  - Sílabos:
      - Sílabo Ética 2025-2: silabo_etica_2025_2.md
      - Sílabo Ética 2026-2: silabo_etica_2026_2.md
  - Matriz de Diseño Instruccional: mdi_matriz_diseno_instruccional.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy

plugins:
  - search
